# Generated by Django 4.2 on 2023-08-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_header_header_products_delete_customhome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_arrived',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_arrived', to='api.shipped'),
        ),
    ]
