# Generated by Django 4.2.4 on 2023-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
