# Generated by Django 4.2.4 on 2023-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_notes_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_buy_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sell_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
