# Generated by Django 4.2.4 on 2023-08-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_total_buy_price_product_total_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_earning',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
