# Generated by Django 4.2 on 2023-09-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_address_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
    ]
